### ISSUE TITLE
Support for Bootstrap themes

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Bootstrap#103]
We must make sure that themes typically used with Bootstrap, such as those [available here](https://themes.getbootstrap.com/), work with Blazor and Blazorade Bootstrap. Themes typically also have multiple skins that can be toggled between, for instance light mode / dark mode.

One possible issue is described in #88.

If it is not feasible to add support for themes in general to Blazorade Bootstrap, then at least we need to produce adequate documentation on what is required to get themes working with Blazor and Blazorade Bootstrap.

**Comment by EvanWeeks** [comment]
Theme use is already possibly simply by including the CSS file you want to use in your index.html or _Host.razor (depending on whether you're using WASM or Server-side). If we're talking about theme-switching, then that can be accomplished with a little bit of JS interop, but I dont know that we want to try to include that in the library. I can't think of a clean way to handle it at the library level without using jQuery to insert and/or alter the `<link>` element dynamically based on the theme chosen (use a `services.AddBlazoradeBootstrap(string theme)` method, where the string is either the name of a known bootstrap theme, or a link to a custom one). I guess that would work, but it's fragile, given that we'd be altering a file in the user's application at runtime, which may or may not already have a link to that CSS or have other CSS, and us with no way of knowing where to insert that `<link>` element to preserve their custom CSS.

**Comment by MikaBerglund** [comment]
I just added this issue because someone reported that a particular theme does not work with Blazorade, or even Blazor. So I just thought we could maybe try out a few themes and see if there would be something that we could add as guidance. It is quite clear that it's not an issue with Blazorade, but if there was an easy fix, we could document it.

**Comment by MikaBerglund** [comment]
The original issue is described in #88. From my perspective you can close this. I'm not that experienced with Bootstrap themes.

**Comment by EvanWeeks** [comment]
I don't think it was ever that a certain theme didn't work with Blazor. It was a case of them trying to hot-switch those themes at runtime, and not finding a good way to do it outside of javascript/jQuery. This isn't a Blazor or Blazorade issue.

**Comment by MikaBerglund** [comment]
Yes I know it's not at least a Blazorade issue, since the same problem was in Blazor without Blazorade too. Let's close this for now, Ok?

**Comment by EvanWeeks** [comment]
Yep, I'm ok with closing it. (I can't close it, myself, I don't have the permissions, which is fine. 😉)
