### ISSUE TITLE
Change Heading.Level to support also numeric and string values

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Bootstrap#104]
The [`Heading`](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Heading) component specifies the level as an enumeration, [`HeadingLevel`](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/HeadingLevel).

After adding a lot of `Heading` components to various UI's, it starts to feel a bit annoying to have to select the enumeration member, when I just could write a number. Every developer knows from the very beginning that there are 6 levels of headings 1-6.

So, instead of writing this:
``` HTML
<Heading Level="HeadingLevel.H3">My Heading</Heading>
```

we would write this instead:
``` HTML
<Heading Level="3">My Heading</Heading>
```

or even something like this:
``` HTML
<Heading Level="h1">My Heading</Heading>
```

It's shorter, more readable, and it probably is no harder to type the number than picking the enum member.

**Comment by MikaBerglund** [comment]
If you have time @EvanWeeks, could you give your opinion about this?

I'm starting to go through the code base with a magnifying glass as we're approaching the end of Q1 and the release date for [v1.0](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Release-v1.0).

I would very much appreciate your input in this matter. There are many other similar cases, where using an enumeration may have been a bit of an overkill, like the [margins and paddings](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/BootstrapComponentBase), that could just as well be a numeric value.

**Comment by EvanWeeks** [comment]
So if the developer puts a "12" there or a "7" or something larger than 6, would we just default it to 6 and put a warning in the browser console? Similarly if they use "0" or "-1", default it to 1 and warn them in the console? 

I would want to make it as drunken-weekend-writing-code resistant as we could, while also letting them know once the hypothetical dev sobered up and looked at their console log that they'd been a moron while plastered on cheap schnapps. 

Not that I would ever do such a thing.

**Comment by MikaBerglund** [comment]
We could always just log a warning and default to something. The Heading already defaults to H1 if you don't specify a level.

In the margin/padding case in #112, we would also need to support "auto" in addition to the numeric values.

The handling of incorrect values can be changed afterwards too without breaking the API, but I would definitely give my vote on logging warnings to make it resistant to those weekend activities 😆

So I guess it's settled then?

**Comment by MikaBerglund** [comment]
Actually we could also set the colour of the heading to NamedColor.Warning to also give a visual hint about the problem. And to take it even further, we would provide some kind of icon next to the header if there are warnings associated with the header, or any other component, and when clicked, it would open up a dialog that would use your markup editor / viewer to show details about what's wrong.

That would probably need to be an opt-in feature through a service configured in Startup, and injected into each component.

**Comment by MikaBerglund** [comment]
In fact, we can have both ways of specifying the header level. You can find details in this commit: b2a542e9ff04a88108ee325cabbb536b1c9e985a

Instead of an enum, we have a `HeadingLevel` struct with static properties for H1 ... H6. With structs, we can create implicit conversion operators (which we cannot do with enums) that we could use to make sure that all of the statements below are true.

- 1 = HeadingLevel.H1
- "1" = HeadingLevel.H1
- "h1" = HeadingLevel.H1
- "H1" = HeadingLevel.H1

So, all of the code examples below are valid and usable:

``` HTML
<Heading Level="HeadingLevel.H1">Heading 1</Heading>
<Heading Level="H1">Heading 1</Heading>
<Heading Level="h1">Heading 1</Heading>
<Heading Level="1">Heading 1</Heading>
```

I think this is the best solution to use, also on the other similar cases.
