### ISSUE TITLE
Reorganize components into namespaces

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Bootstrap#116]
Currently, all components in Blazorade Bootstrap are contained in the same namespace. It is already now getting a bit crowded, and we haven't even released the first version.

We need to consider some kind of structuring to allow for future expansion, if we decide to start adding more and more components into the same library. We must keep it simple though.

In order not to have to invent something new, we could use the same categorization that [Bootstrap itself uses](https://getbootstrap.com/docs/4.4/getting-started/introduction/). The namespace `Blazorade.Bootstrap.Components` would contain all the components listed under [Components in the Bootstrap docs](https://getbootstrap.com/docs/4.4/components/). That namespace would then have the following subnamespaces.

- [**Layout**](https://getbootstrap.com/docs/4.4/layout/). For instance `Container`, `Row` and `Column`.
- [**Content**](https://getbootstrap.com/docs/4.4/content/). Components such as `Heading` and other HTML elements.
- [**Utilities**](https://getbootstrap.com/docs/4.4/utilities/). The only component we have is the `CloseModalButton` component, which would need to be renamed actually.

**Comment by MikaBerglund** [comment]
It would be great if you could have a look at this too @EvanWeeks.

**Comment by EvanWeeks** [comment]
Thumbs-up to everything here, from reorganizing into namespaces that mirror Bootstrap documentation categories, to moving standard HTML wrapper components into their own namespace so people can choose whether or not to use them. It would be annoying to go to type `<div>` and intellisense substitutes `<Div>` when that's not what you want.

As for future expansion, I'm of the opinion that the core Blazorade.Bootstrap library should be solely dedicated to wrapping and simplifying Bootstrap, from layout to components. More complex composite controls built USING those tools should be in an Extensions library, or perhaps in multiple Extension libraries. That'd include things like the carousel, markdown/html editors, datagrid, charts, etc.

**Comment by MikaBerglund** [comment]
Yes, it might be better to create separate extension libraries. I'm all for that as long as we don't have one library for every composite component. Maybe create one library for one theme, for instance:
- Content creation (including markup editor etc)
- Syndication, with RSS carousel and others
- Mapping
- Charting

And so on. You get the idea.

**Comment by MikaBerglund** [comment]
I ditched the Html child namespace, because when looking at the [Bootstrap docs for Content](https://getbootstrap.com/docs/4.4/content/), there are a lot of standard HTML elements mentioned there, so I guess it would be just confusing to have both Content and Html child namespaces.

Otherwise continuing as described above.
