### ISSUE TITLE
Use Blazorade Bootstrap to document Blazorade Bootstrap

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Bootstrap#121]
Currently, the documentation for Blazorade Bootstrap is maintained on the [wiki](https://github.com/Blazorade/Blazorade-Bootstrap/wiki) associated with the repository.

To showcase the versatility of the library, we could produce the documentation for Blazorade Bootstrap using the library itself. This could be a part of the showroom application where we would have one section for the reference documentation, and another section showcasing the components and how they are used.

Most of the reference documentation could be generated from `Blazorade.Bootstrap.Components.xml` documentation file, which is generated from the XML documentation added to the library. This way, we would only need to maintain documentation in one place, together with the actual code, instead of maintaining a completely separate documentation, like the wiki currently is. This will very easily lead to the documentation being out of sync.

[Design-time T4 Text Templates](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates#design-time-t4-text-templates) could be one way of producing the documentation.

**Comment by EvanWeeks** [comment]
Excellent idea!

**Comment by MikaBerglund** [comment]
The first preview version of this documentation is now available at [blazorade.com](https://www.blazorade.com/). It's not going to be just for Blazorade Bootstrap, but a collection of all documentation for all of the future Blazorade libraries.

This is just an early preview, but it already contains reference documentation for components and other types, which is based on reflection and the XML docs embedded in the libraries.

The source code is available in [this repo](https://github.com/Blazorade/blazorade.github.io/tree/master/src).

**Comment by MikaBerglund** [comment]
That website is also a progressive web app implemented as a Blazor WASM app, so you can install it locally on your computer, and use it even offline.

Works on mobile phones too.

**Comment by MikaBerglund** [comment]
I'm closing this now, since this will be handled on the [blazorade.com](https://www.blazorade.com/) site. The documentation for Blazorade libraries is defined in [this issue](https://github.com/Blazorade/blazorade.github.io/issues/8).
