### ISSUE TITLE
Suggestion on Wording on blazorade.com demo page

### ISSUE THREAD

**Issue by toddalbers** [Blazorade/Blazorade-Bootstrap#154]
I have a "small" suggestion on the wording on your Bazorade demo page found at the following link.

https://www.blazorade.com/Blazorade-Bootstrap/

You may want to change the following:

> This is a Blazor WebAssembly application demonstrating the use of the Blazorade Bootstrap component library.

And change it to read something like the following.  Help to make it clear that it works with both WebAssembly and Server.  When I first read your description above, I thought it was for WebAssembly only.  But, then I saw elsewhere that it runs on both.

> Blazorade works with both Blazor WebAssembly and Blazor Server.  This is a Blazor application demonstrating the use of the Blazorade Bootstrap component library with Webassembly.  

Just a suggestion.

Thanks,
Todd Albers

**Comment by MikaBerglund** [comment]
That is an excellent point! Thanks for noticing this. This will definitely go into implementation.

**Comment by MikaBerglund** [comment]
The fix has now been published to the showroom app at https://www.blazorade.com/Blazorade-Bootstrap/

Thanks for the suggestion!

**Comment by toddalbers** [comment]
Sure thing!  Glad you found it helpful.
