### ISSUE TITLE
Tooltips and Popovers?

### ISSUE THREAD

**Issue by robertmclaws** [Blazorade/Blazorade-Bootstrap#159]
This library looks really neat and much cleaner than the other ones I've seen. Will there be support for Tooltips and Popovers? We use them heavily in the Knockout site I'm trying to port to Blazor.

Thanks!

**Comment by MikaBerglund** [comment]
Yes there will be support for both tooltips and popovers.

We are currently finishing up our v1.0 release. We are already feature complete, but we are going through the docs. v1.0 should be out in a couple of days, actually.

After that we're going to start working on [v1.1](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Release-v1.1), which hasn't been outlined that much in detail yet. Currently the plan is to focus on forms and input groups, but I guess we can squeeze in a bit of tooltip and popover.

If you don't mind, I'll close this issue, but create two separate new ones, one for tooltips and one for popovers. Please feel free to add your comments to those and let us know what you feel is important to have.

I'll create those issues first, and link them to this issue before I close this.

**Comment by MikaBerglund** [comment]
These have now been added as separate issues:

- Tooltip: #160 
- Popover: #161 

Both have been sceduled for [v1.1](https://github.com/Blazorade/Blazorade-Bootstrap/milestone/3). Please feel free to add your comments to those. I'll close this issue now with the two new ones opened.
