### ISSUE TITLE
Blazorade Bootstrap Forms

### ISSUE THREAD

**Issue by grantph** [Blazorade/Blazorade-Bootstrap#191]
I've started implementing Bootstrap Forms based on Blazorade in the following fork

https://github.com/grantph/Blazorade-Bootstrap

I used the namespace Blazorade.Bootstrap.Forms for now (easily changed).

I started the implementation by copying the AspnetCore Component Forms, then basing them on BootstrapComponentBase. From there I added the Bootstrap classes, and enhanced on as needed basis. I've tried to implement the Bootstrap classes as close the Bootstrap 4 spec as possible.

The initial controls include

* Form
* CheckBox
* Date
* File (based on Steve Sanderson version)
* Select
* Text
* TextArea
* TextBox (hybrid of Text & TextArea in one control)
* Time

I also have an Icon control based on FontAwesome, and an AutoComplete control based on another Blazor project (can't recall name). I'll consider adding these soon (pending checking licenses) plus a few other controls I missed.

**FormEdit vs Form**

The biggest deviation from AspnetCore is my implementation of Form. I became a little frustrated with FormEdit - being edit only - when what I really wanted was the ability to switch to a read-only version without having to create even more controls. It seemed that what I really wanted was Form control that had Edit or View modes.

Once I developed a based Form control that could be set to Edit or View modes, I wanted to automated further, so I created something called IModelState and ModelState. Any model that implements IModelState will set a ModelStart property to Edit or View. The Form control then recognizes the ModelState and renders form controls in edit or read-only. That means I've been able to change a flag on the model to switch it between view/edit modes, saving me LOTS of time. Think of this like Windows Forms where you're able to switch between edit and view.

**Samples**

Unfortunately, I haven't had time to create Blazorade Forms samples, but I will try to do so in the next few weeks. The implementation will make more sense once you see the samples.

I suppose this issue is more informational so the community can decide if they want to include this Forms implementation, or whether I keep it separate. I'd suggest holding any decision until the samples are up.

**Comment by MikaBerglund** [comment]
Thanks your your interest and input to Blazorade Bootstrap!

Currently we've had to push forward on our schedule with releasing [v1.1](https://github.com/Blazorade/Blazorade-Bootstrap/milestone/3). We have the contents for that release already more or less sorted out, and I think it would be good to try and finish that one up.

After that I'll be more than happy to start looking into these controls that you have been working on too, and integrate them into Blazorade Bootstrap. At some point I think we'll start looking also into common UI components that are not part of Bootstrap, but could be built using the components in Blazorade Bootstrap. That might need to be a separate library though, depending on how experimental it would be.

But the components you are listing above are just standard form controls, so I guess we could look at those in more detail in [v1.2](https://github.com/Blazorade/Blazorade-Bootstrap/milestone/4).

**Comment by MikaBerglund** [comment]
Hi again!

I've been thinking about this lately quite a bit. For now, we will not be pulling this in to Blazorade Boostrap. The components you have listed above are great to have, especially those with rich picker UI etc. However, they are not components that are defined in Bootstrap. Bootstrap has [input groups](https://getbootstrap.com/docs/4.5/components/input-group/) and [form groups](https://getbootstrap.com/docs/4.5/components/forms/#form-groups) in the form section, but they use normal `input` controls.

We already have the [`InputGroup`](https://github.com/Blazorade/Blazorade-Bootstrap/blob/master/Blazorade.Bootstrap.Components/InputGroup.razor) component implemented, and we'll be adding probably a `FormGroup` component as well. That component would then, like the InputGroup component, allow you to use whatever input component you like. That could be either the Razor components that ship with ASP.NET Core (those that require an ambient `Form` component), or just plain `<input />` elements that you then wire up however you need to do.

Now it would be great though to have a separate library, that builds on Blazorade Bootstrap and creates all kinds of different components. They could be different pickers or input controls, or other types of components that build on top of the components defined in Blazorade Bootstrap.

So, I hope you understand my rationale here for not including these form components in Blazorade Bootstrap. I hope you still can find the library useful and worth building solutions on. I'll close this issue now, but feel free to add any additional comments to it.
